name: portfolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  #*Icons
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0

  #*Architecture
  stacked: ^1.7.7
  stacked_services: ^0.6.6
  responsive_builder: 0.3.0
  get_it: 5.0.6
  injectable:
  flutter_hooks:

  #*Services
  url_launcher: 5.7.10

  #*Utilities
  collapsible_sidebar: ^1.0.7+2
  animated_text_kit: ^3.1.0
  lottie:
  simple_animations:

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 1.0.7
  auto_route_generator: 0.6.10
  build_runner: 1.11.1
  change_app_package_name:
flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https:#flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https:#flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https:#flutter.dev/custom-fonts/#from-packages
